# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sitelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelayout',
            name='avatar',
            field=models.FilePathField(),
        ),
    ]
