# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170722_0508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteLayout',
        ),
    ]
